FROM python:3.8-alpine
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install yaqd-attune
RUN mkdir -p root/.config/yaqd/attune/
COPY ./config.toml root/.config/yaqd/attune/config.toml
CMD ["yaqd-attune"]
