FROM python:3.8-slim-buster
RUN apt update
RUN apt install -y git
RUN pip install git+https://gitlab.com/yaq/yaqd-attune@dependent
RUN mkdir -p root/.config/yaqd/attune-delay/
COPY ./config.toml root/.config/yaqd/attune-delay/config.toml
CMD ["yaqd-attune-delay"]
