FROM python:3.8-alpine
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install yaqd-fakes
RUN mkdir -p root/.config/yaqd/fake-continuous-hardware/
COPY ./config.toml root/.config/yaqd/fake-continuous-hardware/config.toml
CMD ["yaqd-fake-continuous-hardware"]
