FROM python:3.8-alpine
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install yaqd-fakes
RUN mkdir -p root/.config/yaqd/fake-has-turret/
COPY ./config.toml root/.config/yaqd/fake-has-turret/config.toml
CMD ["yaqd-fake-has-turret"]
